#!/bin/bash
set -e

if [ -z "$1" ]; then
    exec waylock
fi

file="$1"

read -r w h < <(ffprobe -v error -select_streams v:0 \
    -show_entries stream=width,height \
    -of csv=p=0 "$file" | tr ',' ' ')

fps=$(ffprobe -v error -select_streams v:0 \
    -show_entries stream=r_frame_rate \
    -of csv=p=0 "$file" | awk -F/ '{printf "%d", $1/$2}')

exec waylock \
    -animation-fd 3 \
    -animation-width "$w" \
    -animation-height "$h" \
    -animation-fps "$fps" \
    3< <(ffmpeg -nostdin -stream_loop -1 -i "$file" \
         -an -f rawvideo -pix_fmt bgra - 2>/dev/null)
